"""fixing broken stuff

Revision ID: 6da159adafd8
Revises: f1da0c410dee
Create Date: 2023-03-07 20:32:42.231260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6da159adafd8'
down_revision = 'f1da0c410dee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_user')
    op.create_table('business_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], name=op.f('fk_business_user_business_id_business')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_business_user_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_user'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('business_user')
    # ### end Alembic commands ###
