"""business changes

Revision ID: 7f8147b98c56
Revises: 86ee2f7c5a54
Create Date: 2023-03-07 18:07:54.588026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f8147b98c56'
down_revision = '86ee2f7c5a54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('image_file', sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('last_edit', sa.DateTime(), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_business_email'), ['email'])
        batch_op.drop_column('verified')
        batch_op.drop_column('profile_picture')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_business_email'), type_='unique')
        batch_op.drop_column('last_edit')
        batch_op.drop_column('date_created')
        batch_op.drop_column('image_file')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
