"""business address phone

Revision ID: 86ee2f7c5a54
Revises: 72d92fbb4c4f
Create Date: 2023-03-04 22:12:17.863112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86ee2f7c5a54'
down_revision = '72d92fbb4c4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('webpage', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business'))
    )
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('zip', sa.String(length=20), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], name=op.f('fk_address_business_id_business')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_address'))
    )
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_address_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_address_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_address_zip'), ['zip'], unique=False)

    op.create_table('business_user',
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], name=op.f('fk_business_user_business_id_business')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_business_user_user_id_user'))
    )
    op.create_table('phone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_code', sa.String(length=4), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('extension', sa.String(length=20), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], name=op.f('fk_phone_business_id_business')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_phone'))
    )
    op.create_table('service_business',
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['business.id'], name=op.f('fk_service_business_business_id_business')),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], name=op.f('fk_service_business_service_id_service'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_business')
    op.drop_table('phone')
    op.drop_table('business_user')
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_address_zip'))
        batch_op.drop_index(batch_op.f('ix_address_state'))
        batch_op.drop_index(batch_op.f('ix_address_city'))

    op.drop_table('address')
    op.drop_table('business')
    # ### end Alembic commands ###
