"""business url

Revision ID: a0ecd83b0d04
Revises: 6da159adafd8
Create Date: 2023-03-09 19:29:01.620518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0ecd83b0d04'
down_revision = '6da159adafd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=60), nullable=True))

    
    op.execute("UPDATE public.business SET url = email")

    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.alter_column('url', nullable=False)
        batch_op.create_unique_constraint(batch_op.f('uq_business_url'), ['url'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_business_url'), type_='unique')
        batch_op.drop_column('url')

    # ### end Alembic commands ###
