"""business_user model

Revision ID: f1da0c410dee
Revises: 7f8147b98c56
Create Date: 2023-03-07 19:56:46.567754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1da0c410dee'
down_revision = '7f8147b98c56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_user', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
